### ISSUE TITLE
Image from assets folder

### ISSUE THREAD

**Issue by EmmaTope** [dschuermann/html-textview#10]
How can one get images from assets folder used in src attribute of <img/> tag to load

**Comment by dschuermann** [comment]
Why not put them in raw?

**Comment by EmmaTope** [comment]
the text that forms the HTML come from an Sqlite database. the images are much, the image to be shown is dependent on some factors.

**Comment by dschuermann** [comment]
Not sure what that has to do with the placement of the images. Shouldn't matter if they are in ``raw`` or ``assets``.

**Comment by dschuermann** [comment]
See http://stackoverflow.com/questions/9544737/read-file-from-assets if you still want to read from assets

**Comment by EmmaTope** [comment]
thank you
